# SPDX-FileCopyrightText: 2024 The Forkbomb Company
#
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
  be:
    image: starters-pb:latest
    build:
      context: ./
      dockerfile: ./admin/Dockerfile
    ports:
      - 8090:8090
    volumes:
      - type: bind
        source: ./admin/pb_public
        target: /app/pb_public
      - type: bind
        source: ./admin/pb_migrations
        target: /app/pb_migrations
      - type: bind
        source: ./admin/pb_hooks
        target: /app/pb_hooks
      - type: bind
        source: ./admin/pb_data
        target: /app/pb_data
    stdin_open: true
    tty: true
  fe:
    depends_on: 
      - be
    image: starters-fe
    build:
      context: ./
      dockerfile: ./webapp/Dockerfile
    environment:
      - PUBLIC_POCKETBASE_URL=http://127.0.0.1:8090/
      - PB_ADMIN_USER=admin@example.org
      - PB_ADMIN_PASS=adminadmin
      - PB_TYPEGEN_URL=http://127.0.0.1:8090
      - PB_TYPEGEN_EMAIL=admin@example.org
      - PB_TYPEGEN_PASSWORD=adminadmin
    volumes:
      - type: bind
        source: ./admin/pb_data
        target: /admin/pb_data
    network_mode: "host"
    healthcheck:
      test: wget -nv -t1 --spider 'http://localhost:4173/' || exit 1
      interval: 20s
      retries: 6
      start_period: 60s
      timeout: 60s
