name: docker
on:
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  docker-test:
    name: 🧪 on 🐳
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - run: docker compose up --wait
      - name: 📨 Run playwright
        run: |
          npm install -g pnpm
          pnpm i
          pnpm exec playwright install --with-deps
          pnpm exec playwright test
        working-directory: ./webapp
