# SPDX-FileCopyrightText: 2024 The Forkbomb Company
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: docker
on:
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  docker-test:
    name: 🧪 on 🐳
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - run: docker compose up --wait
      - uses: dyne/pnpm@main
        working-directory: ./webapp
      - name: 📨 Run playwright
        run: |
          pnpm exec playwright install --with-deps
          pnpm exec playwright test
        working-directory: ./webapp
