name: 📢 Release & Publish
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read # for checkout@v4

jobs:
  test:
    name: 🧪
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: dyne/pnpm@main
        with:
          working-directory: webapp
      - run: npx playwright install --with-deps
      - run: pnpm t
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10

  release:
    name: 🔖
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: dyne/pnpm@v1
      - run: pnpm build
      - run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


